default:
  image: node:20

stages:
  - test
  - deploy
  - build-push
  - pack

.ssh_defaults:
  image: kroniak/ssh-client
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $REMOTE_PORT $REMOTE_HOST >> ~/.ssh/known_hosts
    - chmod 664 ~/.ssh/known_hosts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint-job:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run lint

build-push:
  needs: [lint-job]
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: manual
  image: docker:20.10

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''

  services:
    - docker:20.10.16-dind
  stage: pack

  before_script:
    - export IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - time docker build -t $IMAGE -f docker/Dockerfile .
    - docker push $IMAGE

deploy:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: manual
  extends: .ssh_defaults
  stage: deploy
  script:
    - echo CI_COMMIT_TAG=$CI_COMMIT_TAG > tag.env
    - ssh $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT rm -fr questionnaire
    - ssh $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT mkdir -p questionnaire/docker
    - scp -P $REMOTE_PORT "docker/docker-compose.yml" $REMOTE_USER@$REMOTE_HOST:questionnaire/docker/docker-compose.yml
    - scp -P $REMOTE_PORT "tag.env" $REMOTE_USER@$REMOTE_HOST:questionnaire/tag.env
    - scp -P $REMOTE_PORT "deploy.sh" $REMOTE_USER@$REMOTE_HOST:questionnaire/deploy.sh
    - ssh $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT ./questionnaire/deploy.sh
