stages:
  - install
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - client/sProject/node_modules/
    - server/questionnaire/node_modules/

install:
  stage: install
  script:
    - cd client/sProject
    - npm ci --legacy-peer-deps
    - cd ../../server/questionnaire
    - npm ci --legacy-peer-deps

lint:
  stage: test
  script:
    - cd server/questionnaire
    - npm run lint

build:
  stage: build
  needs: [lint, test]
  script:
    - cd client/sProject
    - npm run build
    - cd ../../server/questionnaire
    - npm run build
  artifacts:
    paths:
      - client/sProject/dist
      - server/questionnaire/dist

