stages:
  - install
  - test
  - build

variables:
  NODE_ENV: 'production'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - client/sProject/node_modules/
    - server/questionnaire/node_modules/

install:
  stage: install
  script:
    - npm install -g npm@6.14.8
    - cd client/sProject
    - npm ci
    - cd ../../server/questionnaire
    - npm ci 

lint:
  stage: test
  script:
    - cd client/sProject
    - npm run lint
    - cd ../../server/questionnaire
    - npm run lint

test:
  stage: test
  script:
    - cd client/sProject
    - npm run test
    - cd ../../server/questionnaire
    - npm run test

build:
  stage: build
  needs: [lint, test]
  script:
    - cd client/sProject
    - npm run build
    - cd ../../server/questionnaire
    - npm run build
  artifacts:
    paths:
      - client/sProject/dist
      - server/questionnaire/dist

