default:
  image: node:20

stages:
  - test
  - build-push
  - pack

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint-job:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run lint

build-push:
  needs: [lint-job]
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: manual
  image: docker:20.10

  variables:
    DOCKER_HOST: tcp://docker:2501
    DOCKER_TLS_CERTDIR: ''

  services:
    - docker:20.10.16-dind
  stage: pack

  before_script:
    - export IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - time docker build -t $IMAGE -f docker/Dockerfile .
    - docker push $IMAGE
