version: '3'
name: questionnaire
services:
  backend:
    restart: unless-stopped
    image: registry.qpilipp.ru/psu-mkr-2024/5-fanclub/questionnaire:${CI_COMMIT_TAG:?error}
    environment:
      - SQL_DIALECT=postgres
      - SQL_LOGGING=true
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_NAME=questionnaire
      - DATABASE_PASSWORD=6666
      - DATABASE_PORT=5432
      - JWT_SECRET=secret-secret
    networks:
      - quest-net
    ports:
      - 5172:3000
    volumes:

  frontend:
    restart: unless-stopped
    image: registry.qpilipp.ru/psu-mkr-2024/5-fanclub/questionnaire-client:${CI_COMMIT_TAG:?error}
    ports:
      - 5173:5555
    networks:
      - quest-net
    volumes:
    
  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - questionnaire_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6666
      - POSTGRES_USER=postgres
      - POSTGRES_DB=questionnaire
    networks:
      - quest-net

volumes:
  questionnaire_data:

networks:
  questionnaire-net:
