version: '3'
name: questionnaire
services:
  app:
    restart: unless-stopped
    image: registry.qpilipp.ru/psu-mkr-2024/5-fanclub/questionnaire:${CI_COMMIT_TAG:?error}
    ports:
      - 4550:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - quest-net
    volumes:

  db:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - '4551:5432'
    volumes:
      - questionnaire_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6666
    networks:
      - questionnaire-net

volumes:
  questionnaire_data:

networks:
  questionnaire-net:
