version: '3'
name: questionnaire
services:
  backend:
    restart: unless-stopped
    image: registry.qpilipp.ru/psu-mkr-2024/5-fanclub/questionnaire-server:${CI_COMMIT_TAG:?error}
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - quest-net
    volumes:

  frontend:
    restart: unless-stopped
    image: registry.qpilipp.ru/psu-mkr-2024/5-fanclub/questionnaire-client:${CI_COMMIT_TAG:?error}
    ports:
      - 5173:5555
    environment:
      - API_HOST=backend
      - API_PORT=3000
    networks:
      - quest-net
    volumes:
    
  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - questionnaire_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6666
    networks:
      - questionnaire-net

volumes:
  questionnaire_data:

networks:
  questionnaire-net:
